# Generated by Django 4.1.6 on 2023-03-11 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_settings'),
    ]

    operations = [
        migrations.RenameField(
            model_name='settings',
            old_name='name',
            new_name='settings',
        ),
        migrations.RemoveField(
            model_name='settings',
            name='type',
        ),
        migrations.RemoveField(
            model_name='settings',
            name='value',
        ),
    ]
