# Generated by Django 4.1.6 on 2023-03-11 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_rename_name_settings_settings_remove_settings_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settings',
            name='settings',
            field=models.TextField(),
        ),
    ]
