# Generated by Django 4.1.6 on 2023-03-13 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_settings_settings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotspots',
            name='rfcid',
        ),
    ]
