# Generated by Django 4.1.6 on 2023-03-13 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_hotspots_height'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotspots',
            name='height',
            field=models.DecimalField(decimal_places=0, max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='hotspots',
            name='lat',
            field=models.DecimalField(blank=True, decimal_places=13, max_digits=17, null=True),
        ),
        migrations.AlterField(
            model_name='hotspots',
            name='lon',
            field=models.DecimalField(blank=True, decimal_places=13, max_digits=17, null=True),
        ),
    ]
